name: Deploy to Linux Server

on:
  push:
    branches:
      - master  # main 브랜치에 push될 때 동작

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설치
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # 3. Maven 빌드
      - name: Build with Maven
        run: |
          export MAVEN_OPTS="-Dfile.encoding=UTF-8"
          mvn clean package

      # 4. WAR 파일 배포 (Linux 서버로 전송)
      - name: Deploy WAR file to Linux Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}  # Linux 서버 IP 주소
          username: ${{ secrets.SERVER_USER }}  # 서버 사용자명
          key: ${{ secrets.SERVER_SSH_KEY }}  # SSH private key (GitHub Secrets에 저장)
          source: target/*.war  # Maven 빌드 결과물
          target: /path/to/tomcat/webapps/  # Tomcat webapps 경로

      # 5. Tomcat 재시작 (Linux 서버에서 SSH로 실행)
      - name: Restart Tomcat
        run: |
          ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          sudo systemctl restart tomcat
          EOF
